package com.webjema.models;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import java.util.Date;

@Data
@DynamoDBTable(tableName="DonorsDocuments")
public class DocumentDataModel {
    @DynamoDBHashKey(attributeName="DonorName")
    public String donorName;

    @DynamoDBRangeKey(attributeName="DocumentLink")
    public String documentLink;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute
    public Date foundDate;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute
    public Date updateDate;

}